<?php declare( strict_types = 1 );
namespace CodeKandis\MinecraftManager\Frontend\Templates\Plain;

$htmlTitle = 'Index';
require_once __DIR__ . '/Common/htmlHeader.phtml';
?>
	<body>
	<div id="page">
		<nav class="header">
			<?php
			require_once __DIR__ . '/Common/navigation.phtml';
			?>
		</nav>
		<h1><?php echo $htmlTitle; ?></h1>
		<div id="applicationComponents">
			<div data-control-type="TAB_CONTROL">
				<nav data-control-type="TAB_CONTROL_HEADERS"></nav>
				<div data-control-type="TAB_CONTROL_PAGES">
					<?php
					require_once __DIR__ . '/Components/subwayRailsMapper.phtml';
					require_once __DIR__ . '/Components/subwayStationMapper.phtml';
					require_once __DIR__ . '/Components/settings.phtml';
					?>
				</div>
			</div>
		</div>
	</div>
	</body>
	<?php
require_once __DIR__ . '/Common/htmlFooter.phtml';
