<?php declare( strict_types = 1 );
namespace CodeKandis\MinecraftManager\Frontend\Templates\Plain;

$htmlTitle = 'Signin';
require_once __DIR__ . '/Common/htmlHeader.phtml';
?>
	<body>
	<div id="page">
		<h1><?php echo $htmlTitle; ?></h1>
		<form action="./" method="POST" enctype="multipart/form-data">
			<div>
				<label for="eMail">
					E-Mail<br/>
					<input type="text" name="id" required="required"/>
				</label>
			</div>
			<div>
				<label for="password">
					Password<br/>
					<input type="password" name="password" required="required"/>
				</label>
			</div>
			<div>
				<input type="submit" value="Sign In">
			</div>
		</form>
	</div>
	</body>
	<?php
require_once __DIR__ . '/Common/htmlFooter.phtml';
