<?php declare( strict_types = 1 );
namespace CodeKandis\MinecraftManager\Frontend\Templates\Plain\Components;
?>
<div data-control-type="TAB_CONTROL_PAGE">
	<label data-control-type="TAB_CONTROL_PAGE_HEADER" for="tabPageSettings">Settings</label>
	<input data-control-type="TAB_CONTROL_PAGE_ACTIVATOR" id="tabPageSettings" name="applicationComponent" type="radio"/>
	<form data-control-type="TAB_CONTROL_PAGE_CONTENT" id="settings">
		<section id="settings-defaultValues">
			<h2>Default Values</h2>
			<fieldset>
				<label for="settings-chunkSize">Chunksize</label><input id="settings-chunkSize" name="settings-chunkSize" type="text" required/>
			</fieldset>
		</section>
	</form>
</div>
