<?php declare( strict_types = 1 );
namespace CodeKandis\MinecraftManager\Frontend\Templates\Plain\Components;
?>
<div data-control-type="TAB_CONTROL_PAGE">
	<label data-control-type="TAB_CONTROL_PAGE_HEADER" for="tabPageSettings">Settings</label>
	<input data-control-type="TAB_CONTROL_PAGE_ACTIVATOR" id="tabPageSettings" name="applicationComponent" type="radio"/>
	<form data-control-type="TAB_CONTROL_PAGE_CONTENT" id="settings">
		<section id="settings-defaultValues">
			<h2>Default Values</h2>
			<fieldset>
				<label for="settings-chunkSize">Chunksize</label><input id="settings-chunkSize" name="settings-chunkSize" type="text" required/>
			</fieldset>
		</section>
		<section id="settings-initialValues">
			<h2>Initial position</h2>
			<fieldset>
				<label for="settings-initialPositionX">X</label><input id="settings-initialPositionX" name="settings-initialPositionX" type="text" required/>
			</fieldset>
			<fieldset>
				<label for="settings-initialPositionY">Y</label><input id="settings-initialPositionY" name="settings-initialPositionY" type="text" required/>
			</fieldset>
			<fieldset>
				<label for="settings-initialPositionZ">Z</label><input id="settings-initialPositionZ" name="settings-initialPositionZ" type="text" required/>
			</fieldset>
		</section>
	</form>
</div>
