<?php declare( strict_types = 1 );
namespace CodeKandis\MinecraftManager\Frontend\Templates\Plain\Components;
?>
<div data-control-type="TAB_CONTROL_PAGE">
	<label data-control-type="TAB_CONTROL_PAGE_HEADER" for="tabPageSubwayRailsMapper">Subway Rails Mapper</label>
	<input data-control-type="TAB_CONTROL_PAGE_ACTIVATOR" id="tabPageSubwayRailsMapper" name="applicationComponent" type="radio"/>
	<form data-control-type="TAB_CONTROL_PAGE_CONTENT" id="subwayRailsMapper">
		<section id="subwayRailsMapper-positionCurrent">
			<h2>Current Position</h2>
			<fieldset>
				<label for="subwayRailsMapper-currentX">X</label><input id="subwayRailsMapper-currentX" name="subwayRailsMapper-currentX" type="text" required/>
			</fieldset>
			<fieldset>
				<label for="subwayRailsMapper-currentY">Y</label><input id="subwayRailsMapper-currentY" name="subwayRailsMapper-currentY" type="text" required/>
			</fieldset>
			<fieldset>
				<label for="subwayRailsMapper-currentZ">Z</label><input id="subwayRailsMapper-currentZ" name="subwayRailsMapper-currentZ" type="text" required/>
			</fieldset>
		</section>
		<section id="subwayRailsMapper-calculatedValues">
			<h2>Calculated Values</h2>
			<fieldset>
				<label for="subwayRailsMapper-calculatedPositionYPositive">YP</label><input id="subwayRailsMapper-calculatedPositionYPositive" type="text" readonly/>
			</fieldset>
			<fieldset>
				<label for="subwayRailsMapper-calculatedPositionZPositive">ZP</label><input id="subwayRailsMapper-calculatedPositionZPositive" type="text" readonly/>
			</fieldset>
			<fieldset>
				<label for="subwayRailsMapper-calculatedPositionXNegative">XN</label><input id="subwayRailsMapper-calculatedPositionXNegative" type="text" readonly/><label for="subwayRailsMapper-calculatedPositionXPositive">XP</label><input id="subwayRailsMapper-calculatedPositionXPositive" type="text" readonly/>
			</fieldset>
			<fieldset>
				<label for="subwayRailsMapper-calculatedPositionZNegative">ZN</label><input id="subwayRailsMapper-calculatedPositionZNegative" type="text" readonly/>
			</fieldset>
			<fieldset>
				<label for="subwayRailsMapper-calculatedPositionYNegative">YN</label><input id="subwayRailsMapper-calculatedPositionYNegative" type="text" readonly/>
			</fieldset>
		</section>
	</form>
</div>
