<?php declare( strict_types = 1 );
namespace CodeKandis\MinecraftManager\Frontend\Templates\Plain\Common;

use CodeKandis\MinecraftManager\Configurations\FrontendConfigurationRegistry;
use CodeKandis\MinecraftManager\Frontend\Http\UriBuilders\FrontendUriBuilder;

$uriBuilder = new FrontendUriBuilder(
	FrontendConfigurationRegistry
		::_()
		->getUriBuilderConfiguration()
);
?>
<ul>
	<li><a href="<?php echo $uriBuilder->buildSignoutUri(); ?>">Sign Out</a></li>
</ul>
